name: flake8 Lint

on: [push, pull_request]

permissions:
  contents: read

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f
      - name: Set up Python environment
        uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435
        with:
          python-version: "3.11"
      - name: flake8 Lint
        uses: py-actions/flake8@2014ef764424fd7699d615323c17836092bec9b9
        with:
          ignore: "F401"
          max-line-length: "100"
