name: flake8 Lint

on: [push, pull_request]

permissions:
  contents: read

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - name: Set up Python environment
        uses: actions/setup-python@57ded4d7d5e986d7296eab16560982c6dd7c923b
        with:
          python-version: "3.11"
      - name: flake8 Lint
        uses: py-actions/flake8@2014ef764424fd7699d615323c17836092bec9b9
        with:
          ignore: "F401"
          max-line-length: "100"
