on:
  push:
    tags:
      - v1.**
      
jobs:
  make_release:
    name: Create a GitHub release
    runs-on: ubuntu-latest
    steps:
      - name: Create a github release
        uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Changes in this Release:
          draft: false
          prerelease: false
