name: test-push

on:
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  
jobs:
  build_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f
      - uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435  # v4.5.0
        with:
          python-version: 3.8
          architecture: x64
      - name: Build package
        run: |
          pip install build==0.10.0
          python -m build
      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          name: test-package
          path: dist/*
