name: test-push

on:
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  
jobs:
  build_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - uses: actions/setup-python@bd6b4b6205c4dbad673328db7b31b7fab9e241c0  # v4.6.1
        with:
          python-version: 3.8
          architecture: x64
      - name: Build package
        run: |
          pip install build==0.10.0
          python -m build
      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          name: test-package
          path: dist/*
